server:
  port: 8085

spring:
  reactor:
    context-propagation: auto

  cloud:
    gateway:

    
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthFilter
              args:
                required: false

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtAuthFilter
              args:
                required: true
                roles:
                  - ADMIN
                  - USER

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtAuthFilter
              args:
                required: true
                roles:
                  - ADMIN
                  - USER

        - id: INVENTORY-ADMIN
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - name: JwtAuthFilter
              args:
                required: true
                roles: [ADMIN]

        - id: VIEW-PRODUCTS
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: JwtAuthFilter
              args:
                required: false

jwt:
  secret: ${JWT_SECRET}
