spring:
  datasource:
    hikari:
      initializationFailTimeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      
  elasticsearch:
    uris: http://elasticsearch:9200

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

logstash:
  host: logstash 

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

