spring:
  elasticsearch:
    uris: http://elasticsearch:9200

zipkin:
  endpoint: http://zipkin:9411/api/v2/spans

logstash:
  host: logstash

logging:
  level:
    root: WARN

management:
  tracing:
    sampling:
      probability: 1.0 

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
