spring:    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  datasource:
    hikari:
      initializationFailTimeout: 60000
      connectionTimeout: 30000

logging:
  level:
    io.github.resilience4j: WARN
