spring:
  datasource:
    hikari:
      initializationFailTimeout: 60000
      connectionTimeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    io.github.resilience4j: WARN
