server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, prometheus, circuitbreakerevents

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      inventoryService:
        max-attempts: 3
        wait-duration: 3s

        retry-exceptions:
          - feign.RetryableException

        ignore-exceptions:
          - com.ahesan.ecommerce.order_service.exception.InsufficientStockException
          - com.ahesan.ecommerce.order_service.exception.ExternalServiceException

  ratelimiter:
    instances:
      orderRateLimiter:
        limit-refresh-period: 10s
        limit-for-period: 1
        timeout-duration: 0s
